scope: knb-lter-cap
identifier: 652
baseURL: https://data.gios.asu.edu/datasets/cap/
project: lter
title: 'Ecological Survey of Central Arizona: a survey of key ecological indicators in the greater Phoenix metropolitan area and surrounding Sonoran desert, ongoing since 1999'
maintenance: regular
geographic_description: 'CAP LTER study area: greater Phoenix, Arizona (USA) metropolitan area and surrounding Sonoran desert region'
