default:
  user: "srearl"
  plots: "kobo/ESCA_plot_2024-04-22-18-29-03-ESCA_plot.csv"
  parcels: "kobo/ESCA_parcel_2024-04-22-18-38-10-ESCA_parcel.csv"
  plot_hs: "kobo/ESCA_plot_2024-04-22-18-29-03-hs_structure_repeat.csv"
  parcel_hs : "kobo/ESCA_parcel_2024-04-22-18-38-10-hs_structure_repeat.csv"
  plot_synoptic: "kobo/ESCA_plot_2024-04-22-18-29-03-synoptic_photos_repeat.csv"
  parcel_synoptic: "kobo/ESCA_parcel_2024-04-22-18-38-10-synoptic_photos_repeat.csv"
  plot_lse : "kobo/ESCA_plot_2024-04-22-18-29-03-lse_repeat.csv"
  parcel_lse : "kobo/ESCA_parcel_2024-04-22-18-38-10-lse_repeat.csv"
  front_back : "kobo/ESCA_parcel_2024-04-22-18-38-10-front_back_yard_repeat.csv"
  shrub_survey: "kobo/ESCA_shrub_survey_2024-04-22-19-46-58-ESCA_shrub_survey.csv"
  shrub_repeat: "kobo/ESCA_shrub_survey_2024-04-22-19-46-58-shrub_measurement_repeat.csv"
  shrub_measures: "kobo/ESCA_shrub_survey_2024-04-22-19-46-58-shrub_measurement_repeat_001.csv"
  shrub_count_images: "kobo/ESCA_shrub_survey_2024-04-22-19-46-58-shrub_count_image_repeat.csv"
  shrub_survey_images: "kobo/ESCA_shrub_survey_2024-04-22-19-46-58-shrub_survey_image_repeat.csv"
  tree_repeat: "kobo/ESCA_tree_survey_2024-04-22-18-39-45-tree_survey_repeat.csv"
  tree_survey: "kobo/ESCA_tree_survey_2024-04-22-18-39-45-ESCA_tree_survey.csv"
  tree_images: "kobo/ESCA_tree_survey_2024-04-22-18-39-45-tree_survey_image_repeat.csv"
  annuals_repeat: "kobo/ESCA_annuals_2024-04-22-20-05-55-annuals_repeat.csv"
  annuals_survey: "kobo/ESCA_annuals_2024-04-22-20-05-55-ESCA_annuals.csv"
  annuals_images: "kobo/ESCA_annuals_2024-04-22-20-05-55-annuals_images_repeat.csv"