# README ------------------------------------------------------------------

# This workflow details the processing and insertion of raw TRAACS data from the
# 2000 Survey 200 into the survey200 postgres database. The raw data files
# (included in this repository) were generated by hand-entering raw machine
# output read from files into a spreadhseet as the raw machine output was not
# available in digital format.

# Because there are not 2000 soil data in the survey200 database, these raw data
# are added to the soil_traacs table without a soil_sample_id.

# Note that soil data from the 2000 survey are NOT included in knb-lter-cap.652.
# These raw data and the processing of them are included here on account of (a)
# the changes to the esca database, and (b) as this repository is essentially
# becoming the central source of data and information regarding the esca
# project. Recall that the soil data from the 2000 survey were published
# separately (knb-lter-cap.281) owing to considerable differences in approaches
# in subsequent surveys. These data and this workflow will be included in the
# zipped knb-lter-cap.281 as well for completeness.

# libraries ----
library(readxl)
library(stringr)
library(tidyverse)
library(RPostgreSQL)
library(zoo)
library(tools)


# postgres ----
source('~/Documents/localSettings/pg_prod.R')
source('~/Documents/localSettings/pg_local.R')

pg <- pg_prod
pg <- pg_local


# perimeter, raw traacs phos data ----------------------------------------------

raw_traacs_phosphorus <- bind_rows(
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 1) %>% 
    mutate(sample_set = 1),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 2) %>% 
    mutate(sample_set = 2),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 3) %>% 
    mutate(sample_set = 3),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 4) %>% 
    mutate(sample_set = 4),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 5) %>% 
    mutate(sample_set = 5),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 6) %>% 
    mutate(sample_set = 6),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 7) %>% 
    mutate(sample_set = 7),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 8) %>% 
    mutate(sample_set = 8),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 9) %>% 
    mutate(sample_set = 9),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 10) %>% 
    mutate(sample_set = 10),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 11) %>% 
    mutate(sample_set = 11),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 SRP Traacs Raw Data.xls', sheet = 12) %>% 
    mutate(sample_set = 12)
) %>% 
  mutate(
    survey_year = 2000,
    analyte = 'phosphorus'
  ) %>% 
  filter(!is.na(`mg P/L`))

raw_traacs_phosphorus <- raw_traacs_phosphorus %>% 
  mutate(code_layer = str_extract(Sample, '^(\\S{2,5})\\s(TOP|BOT)')) %>% 
  separate(code_layer, into = c("site_code", "deep_core_type"), sep = " ") %>% 
  rename_all(tolower) %>%
  mutate(
    deep_core_type = case_when(
      grepl("top", deep_core_type, ignore.case = T) ~ 'top',
      grepl("bot", deep_core_type, ignore.case = T) ~ 'bottom'
    ),
    sample_set = as.integer(sample_set)
  ) %>% 
  select(deep_core_type, sample_id = sample, sample_set, conc_mg_l = `mg p/l`, survey_year, analyte)
  
dataname <- raw_traacs_phosphorus 

if (dbExistsTable(pg, c('survey200', 'temp_traacs'))) dbRemoveTable(pg, c('survey200', 'temp_traacs')) # make sure tbl does not exist
dbWriteTable(pg, c('survey200', 'temp_traacs'), value = dataname, row.names = F)

insert_traacs_2000_query <- '
INSERT INTO survey200.soil_traacs (
  sample_id,
  sample_set,
  conc_mg_l,
  survey_year,
  analyte
)
(
  SELECT
    sample_id,
    sample_set,
    conc_mg_l,
    survey_year,
    analyte
  FROM survey200.temp_traacs 
);'

# insert data
dbExecute(pg, insert_traacs_2000_query)

# clean up
if (dbExistsTable(pg, c('survey200', 'temp_traacs'))) dbRemoveTable(pg, c('survey200', 'temp_traacs')) # clean up


# perimeter, raw traacs nitrate data ----------------------------------------------

raw_traacs_nitrate <- bind_rows(
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 1, col_types = c("text", "text")) %>% 
    mutate(sample_set = 1),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 2, col_types = c("text", "text")) %>% 
    mutate(sample_set = 2),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 3, col_types = c("text", "text")) %>% 
    mutate(sample_set = 3),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 4, col_types = c("text", "text")) %>% 
    mutate(sample_set = 4),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 5, col_types = c("text", "text")) %>% 
    mutate(sample_set = 5),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 6, col_types = c("text", "text")) %>% 
    mutate(sample_set = 6),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 7, col_types = c("text", "text")) %>% 
    mutate(sample_set = 7),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 8, col_types = c("text", "text")) %>% 
    mutate(sample_set = 8),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 9, col_types = c("text", "text")) %>% 
    mutate(sample_set = 9),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 10, col_types = c("text", "text")) %>% 
    mutate(sample_set = 10),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 11, col_types = c("text", "text")) %>% 
    mutate(sample_set = 11),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 12, col_types = c("text", "text")) %>% 
    mutate(sample_set = 12),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NO3 Traacs raw data.xls', sheet = 13, col_types = c("text", "text")) %>% 
    mutate(sample_set = 13)
) %>% 
  mutate(
    survey_year = 2000,
    analyte = 'nitrate',
    `mg N/L` = as.numeric(`mg N/L`),
    Sample = case_when(
      grepl("LS", Sample) ~ paste0(Sample, "-unidentified"),
      TRUE ~ Sample
    )
  ) %>% 
  filter(!is.na(`mg N/L`))

raw_traacs_nitrate <- raw_traacs_nitrate %>% 
  mutate(code_layer = str_extract(Sample, '^(\\S{2,5})\\s(TOP|BOT)')) %>% 
  separate(code_layer, into = c("site_code", "deep_core_type"), sep = " ") %>% 
  rename_all(tolower) %>%
  mutate(
    deep_core_type = case_when(
      grepl("top", deep_core_type, ignore.case = T) ~ 'top',
      grepl("bot", deep_core_type, ignore.case = T) ~ 'bottom'
    ),
    sample_set = as.integer(sample_set),
    sample_sequence = as.integer(NA)
  ) %>% 
  select(deep_core_type, sample_id = sample, sample_set, conc_mg_l = `mg n/l`, survey_year, analyte)

dataname <- raw_traacs_nitrate  

if (dbExistsTable(pg, c('survey200', 'temp_traacs'))) dbRemoveTable(pg, c('survey200', 'temp_traacs')) # make sure tbl does not exist
dbWriteTable(pg, c('survey200', 'temp_traacs'), value = dataname, row.names = F)

insert_traacs_2000_query <- '
INSERT INTO survey200.soil_traacs (
  sample_id,
  sample_set,
  conc_mg_l,
  survey_year,
  analyte
)
(
  SELECT
    sample_id,
    sample_set,
    conc_mg_l,
    survey_year,
    analyte
  FROM survey200.temp_traacs 
);'
  
  # insert data
  dbExecute(pg, insert_traacs_2000_query)
  
  # clean up
  if (dbExistsTable(pg, c('survey200', 'temp_traacs'))) dbRemoveTable(pg, c('survey200', 'temp_traacs')) # clean up
  
# perimeter, raw traacs ammonium data ----------------------------------------------
  
raw_traacs_ammonium <- bind_rows(
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 1, col_types = c("text", "text")) %>% 
    mutate(sample_set = 1),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 2, col_types = c("text", "text")) %>% 
    mutate(sample_set = 2),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 3, col_types = c("text", "text")) %>% 
    mutate(sample_set = 3),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 4, col_types = c("text", "text")) %>% 
    mutate(sample_set = 4),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 5, col_types = c("text", "text")) %>% 
    mutate(sample_set = 5),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 6, col_types = c("text", "text")) %>% 
    mutate(sample_set = 6),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 7, col_types = c("text", "text")) %>% 
    mutate(sample_set = 7),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 8, col_types = c("text", "text")) %>% 
    mutate(sample_set = 8),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 9, col_types = c("text", "text")) %>% 
    mutate(sample_set = 9),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 10, col_types = c("text", "text")) %>% 
    mutate(sample_set = 10),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 11, col_types = c("text", "text")) %>% 
    mutate(sample_set = 11),
  read_excel('./esca_soils_processing_data/soils2000/S200 2000 avail NH4 Traacs raw data.xls', sheet = 12, col_types = c("text", "text")) %>% 
    mutate(sample_set = 12)
) %>% 
  mutate(
    survey_year = 2000,
    analyte = 'ammonium',
    `mg N/L` = as.numeric(`mg N/L`),
    Sample = case_when(
      grepl("LS", Sample) ~ paste0(Sample, "-unidentified"),
      TRUE ~ Sample
    )
  ) %>% 
  filter(!is.na(`mg N/L`))
  
raw_traacs_ammonium <- raw_traacs_ammonium %>% 
  mutate(code_layer = str_extract(Sample, '^(\\S{2,5})\\s(TOP|BOT)')) %>% 
  separate(code_layer, into = c("site_code", "deep_core_type"), sep = " ") %>% 
  rename_all(tolower) %>%
  mutate(
    deep_core_type = case_when(
      grepl("top", deep_core_type, ignore.case = T) ~ 'top',
      grepl("bot", deep_core_type, ignore.case = T) ~ 'bottom'
    ),
    sample_set = as.integer(sample_set),
    sample_sequence = as.integer(NA)
  ) %>% 
  select(deep_core_type, sample_id = sample, sample_set, conc_mg_l = `mg n/l`, survey_year, analyte)
  
  dataname <- raw_traacs_ammonium  
  
  if (dbExistsTable(pg, c('survey200', 'temp_traacs'))) dbRemoveTable(pg, c('survey200', 'temp_traacs')) # make sure tbl does not exist
  dbWriteTable(pg, c('survey200', 'temp_traacs'), value = dataname, row.names = F)
  
insert_traacs_2000_query <- '
INSERT INTO survey200.soil_traacs (
  sample_id,
  sample_set,
  conc_mg_l,
  survey_year,
  analyte
)
(
  SELECT
    sample_id,
    sample_set,
    conc_mg_l,
    survey_year,
    analyte
  FROM survey200.temp_traacs 
);'
  
  # insert data
  dbExecute(pg, insert_traacs_2000_query)
  
  # clean up
  if (dbExistsTable(pg, c('survey200', 'temp_traacs'))) dbRemoveTable(pg, c('survey200', 'temp_traacs')) # clean up
  